Responsive Design -- Tnw clone
keddo/thenextweb-clone pull request #1
Opened 2020-05-09 12:30 UTC by keddo

**Building with Responsive Design**

This project, Consists of  building a responsive website. By cloning The Next Web, a tech-focused magazine.

I am kindly requesting for review.
Thank you.

2020-05-09 19:32 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

You are really close, please implement the changes below for your project to get approved!

### Happy coding! :computer:

## Lucas Mazo

2020-05-09 19:32 UTC, lucasmazo32 commented on index.html
> +                <div class="cover-logo"></div>
The logo crops when I am reducing the size of the page. Kindly fix that.

Screenshot from your page. 

![image](https://user-images.githubusercontent.com/57414789/81482979-69bef900-9200-11ea-9e9e-9c0618534977.png)

2020-05-09 19:32 UTC, lucasmazo32 commented on index.html
> +                        </a>
The letters on the side articles are cropped when reducing the size. Kindly fix that.

> Screenshot from your page.
![image](https://user-images.githubusercontent.com/57414789/81483019-b4407580-9200-11ea-92fa-6b1be98cb05c.png)

2020-05-09 19:32 UTC, lucasmazo32 commented on index.html
> +                    </ul>
When there are only three articles, the text to the side of latest funding should be below.

> Original page
![image](https://user-images.githubusercontent.com/57414789/81483109-4a749b80-9201-11ea-9108-5f8a28ad34be.png)

>Your page
![image](https://user-images.githubusercontent.com/57414789/81483122-54969a00-9201-11ea-99c4-8293bc9d395e.png)

2020-05-11 08:07 UTC, trekab requested changes
# Changes Required!
Hi @keddo, well done on this project so far! However, there are some requirements you need to implement to complete. These are:
## Required:
- [x] Fix [HTML validator](https://validator.w3.org/#validate_by_upload) errors.
- [x] Avoid using inline CSS.
- [x] The logo isn't proportionally sized for large screens.
- [x] Latest news section heading is partially hidden under the top 3 articles section on large screens. Please fix this.
- [x] There should be no small breakpoints. The base styles should be enough for the mobile screen.([screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

## Optional:
- [ ] It is redundant to give the `<main> tag` a class of 'main', and the `<footer> tag` a class of 'footer'. It is ok to use tag selectors in this case. I commend you on the use of semantic HTML. :+1: 

__Kindly work on the required changes and submit another code review request__
_Feel free to contact me on slack about any inquiries regarding this review_ :wink: 
__Treasure Kabareebe__

2020-05-16 08:18 UTC, keddo commented
**Changes made to the above Review:**
* HTML validation errors got fixed
* Inline CSS removed
* Logo fixed to responsive
* Issues related to latest news section fixed
* base style for media queries add.

**Kindly requesting for review.
Thanks**

2020-05-16 20:02 UTC, lucasmazo32 approved these changes
# Project approved :rocket:

#### Great job!

#### Your project looks great!

### You can go ahead and merge this pull request!

### Happy coding! :computer:

## Lucas Mazo

2020-05-17 07:29 UTC, merged